use std::{
    fs,
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

use crate::config::{ConfigError, SentinelConfig};

pub fn write_sentinel_conf(config: &SentinelConfig) -> String {
    let mut out = String::new();
    out.push_str("# Generated by senkodb sentinel\n");
    out.push_str("# Do not edit the sections marked AUTO-GENERATED.\n");
    out.push_str("# Manually configured sections are preserved on rewrite.\n\n");

    out.push_str("# NETWORK\n");
    out.push_str(&format!(
        "protected-mode {}\n",
        yes_no(config.network.protected_mode)
    ));
    out.push_str(&format!("port {}\n", config.network.port));
    if !config.network.bind.is_empty() {
        out.push_str("bind");
        for bind in &config.network.bind {
            out.push(' ');
            out.push_str(bind);
        }
        out.push('\n');
    }
    if let Some(ip) = &config.network.announce_ip {
        out.push_str(&format!("sentinel announce-ip {}\n", quote(ip)));
    }
    if let Some(port) = config.network.announce_port {
        out.push_str(&format!("sentinel announce-port {port}\n"));
    }
    out.push_str(&format!(
        "sentinel resolve-hostnames {}\n",
        yes_no(config.network.resolve_hostnames)
    ));
    out.push_str(&format!(
        "sentinel announce-hostnames {}\n\n",
        yes_no(config.network.announce_hostnames)
    ));

    out.push_str("# GENERAL\n");
    out.push_str(&format!("dir {}\n", quote_path(&config.general.dir)));
    out.push_str(&format!("daemonize {}\n", yes_no(config.general.daemonize)));
    if let Some(pidfile) = &config.general.pidfile {
        out.push_str(&format!("pidfile {}\n", quote_path(pidfile)));
    }
    out.push_str(&format!(
        "loglevel {}\n",
        match config.general.loglevel {
            senko_core::config::LogLevel::Debug => "debug",
            senko_core::config::LogLevel::Verbose => "verbose",
            senko_core::config::LogLevel::Notice => "notice",
            senko_core::config::LogLevel::Warning => "warning",
            senko_core::config::LogLevel::Nothing => "nothing",
        }
    ));
    if let Some(logfile) = &config.general.logfile {
        out.push_str(&format!("logfile {}\n", quote_path(logfile)));
    }
    if config.general.syslog_enabled {
        out.push_str("syslog-enabled yes\n");
        out.push_str(&format!(
            "syslog-ident {}\n",
            quote(&config.general.syslog_ident)
        ));
        out.push_str(&format!(
            "syslog-facility {}\n",
            quote(&config.general.syslog_facility)
        ));
    }
    out.push('\n');

    out.push_str("# SECURITY\n");
    if let Some(requirepass) = &config.security.requirepass {
        out.push_str(&format!("requirepass {}\n", quote(requirepass)));
    }
    if let Some(aclfile) = &config.security.aclfile {
        out.push_str(&format!("aclfile {}\n", quote_path(aclfile)));
    }
    out.push_str(&format!(
        "acllog-max-len {}\n",
        config.security.acllog_max_len
    ));
    for user in &config.security.users {
        out.push_str(user);
        out.push('\n');
    }
    if let Some(user) = &config.security.sentinel_user {
        out.push_str(&format!("sentinel sentinel-user {}\n", quote(user)));
    }
    if let Some(pass) = &config.security.sentinel_pass {
        out.push_str(&format!("sentinel sentinel-pass {}\n", quote(pass)));
    }
    out.push_str(&format!(
        "sentinel deny-scripts-reconfig {}\n\n",
        yes_no(config.security.deny_scripts_reconfig)
    ));

    out.push_str("# MASTERS\n");
    let mut masters = config.masters.iter().collect::<Vec<_>>();
    masters.sort_by(|left, right| left.name.cmp(&right.name));
    for master in masters {
        out.push_str(&format!(
            "sentinel monitor {} {} {} {}\n",
            master.name,
            quote(&master.host),
            master.port,
            master.quorum
        ));
        out.push_str(&format!(
            "sentinel down-after-milliseconds {} {}\n",
            master.name, master.down_after_milliseconds
        ));
        out.push_str(&format!(
            "sentinel parallel-syncs {} {}\n",
            master.name, master.parallel_syncs
        ));
        out.push_str(&format!(
            "sentinel failover-timeout {} {}\n",
            master.name, master.failover_timeout
        ));
        if let Some(pass) = &master.auth_pass {
            out.push_str(&format!(
                "sentinel auth-pass {} {}\n",
                master.name,
                quote(pass)
            ));
        }
        if let Some(user) = &master.auth_user {
            out.push_str(&format!(
                "sentinel auth-user {} {}\n",
                master.name,
                quote(user)
            ));
        }
        if let Some(script) = &master.notification_script {
            out.push_str(&format!(
                "sentinel notification-script {} {}\n",
                master.name,
                quote_path(script)
            ));
        }
        if let Some(script) = &master.client_reconfig_script {
            out.push_str(&format!(
                "sentinel client-reconfig-script {} {}\n",
                master.name,
                quote_path(script)
            ));
        }
        let mut renames = master.rename_commands.iter().collect::<Vec<_>>();
        renames.sort_by(|left, right| left.0.cmp(right.0));
        for (command, renamed) in renames {
            out.push_str(&format!(
                "sentinel rename-command {} {} {}\n",
                master.name,
                command,
                quote(renamed)
            ));
        }
        if master.master_reboot_down_after_period != 0 {
            out.push_str(&format!(
                "sentinel master-reboot-down-after-period {} {}\n",
                master.name, master.master_reboot_down_after_period
            ));
        }
        out.push('\n');
    }

    out.push_str("# AUTO-GENERATED STATE — managed by senkodb, do not edit\n");
    out.push_str(&format!(
        "sentinel current-epoch {}\n",
        config.runtime.current_epoch
    ));
    if let Some(myid) = &config.runtime.myid {
        out.push_str(&format!("sentinel myid {}\n", myid));
    }
    out.push('\n');

    let mut names = config.runtime.masters.keys().collect::<Vec<_>>();
    names.sort();
    for name in names {
        if let Some(runtime) = config.runtime.masters.get(name) {
            out.push_str(&format!("# master: {name}\n"));
            for replica in &runtime.known_replicas {
                out.push_str(&format!(
                    "sentinel known-replica {} {} {}\n",
                    name,
                    quote(&replica.host),
                    replica.port
                ));
            }
            for sentinel in &runtime.known_sentinels {
                out.push_str(&format!(
                    "sentinel known-sentinel {} {} {} {}\n",
                    name,
                    quote(&sentinel.host),
                    sentinel.port,
                    sentinel.runid
                ));
            }
            if let Some(master) = config.find_master(name)
                && (runtime.current_host != master.host || runtime.current_port != master.port)
            {
                out.push_str(&format!(
                    "# Current master address after failover (updated from {}:{})\n",
                    master.host, master.port
                ));
                out.push_str(&format!(
                    "sentinel monitor {} {} {} {}\n",
                    name,
                    quote(&runtime.current_host),
                    runtime.current_port,
                    master.quorum
                ));
            }
            out.push('\n');
        }
    }
    out
}

pub fn flush_sentinel_conf_to_disk(path: &Path, content: &str) -> Result<(), ConfigError> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent)?;
    let tmp = temp_path(path);
    fs::write(&tmp, content)?;
    fs::File::open(&tmp)?.sync_data()?;
    fs::rename(&tmp, path)?;
    fs::File::open(parent)?.sync_data()?;
    Ok(())
}

fn temp_path(path: &Path) -> PathBuf {
    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    path.with_extension(format!("conf.tmp.{unique}"))
}

fn yes_no(value: bool) -> &'static str {
    if value { "yes" } else { "no" }
}

fn quote(value: &str) -> String {
    if value.is_empty() || value.chars().any(char::is_whitespace) {
        let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
        format!("\"{escaped}\"")
    } else {
        value.to_owned()
    }
}

fn quote_path(path: &Path) -> String {
    quote(&path.to_string_lossy())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::conf_parser::parse_sentinel_conf;

    #[test]
    fn writer_round_trips_config() {
        let config = parse_sentinel_conf(
            r#"
            port 26379
            sentinel monitor bmaster 127.0.0.1 6379 2
            sentinel known-replica bmaster 127.0.0.1 6380
            sentinel current-epoch 3
            sentinel myid 0123456789012345678901234567890123456789
        "#,
        )
        .expect("parse");
        let rendered = write_sentinel_conf(&config);
        let reparsed = parse_sentinel_conf(&rendered).expect("reparse");
        assert_eq!(reparsed.runtime.current_epoch, 3);
        assert_eq!(reparsed.runtime.myid, config.runtime.myid);
    }

    #[test]
    fn writer_quotes_passwords_with_spaces() {
        let config = parse_sentinel_conf(
            r#"sentinel monitor mymaster 127.0.0.1 6379 2
               sentinel auth-pass mymaster "my pass word""#,
        )
        .expect("parse");
        let rendered = write_sentinel_conf(&config);
        assert!(rendered.contains("\"my pass word\""));
    }
}
