[package]
name = "senko-prob"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
senko-core = { path = "../senko-core", features = ["prob"] }
bytes = "1"
thiserror = "2"
ahash = "0.8"
parking_lot = "0.12"
smallvec = "1"
fastrand = "1"

[features]
default = []
